import { describe, it, expect } from 'vitest';
import { renderHtml } from '../../src/reporters/htmlReporter.js';
import type { AuditReport } from '../../src/types.js';

// ---------------------------------------------------------------------------
// Mock Data
// ---------------------------------------------------------------------------

const MOCK_REPORT: AuditReport = {
  timestamp: '2023-01-01T00:00:00.000Z',
  rootDir: '/test/project',
  durationMs: 123,
  loc: {
    files: [
      { path: '/test/project/index.ts', relativePath: 'index.ts', language: 'TypeScript', sizeBytes: 100, content: '', },
    ],
    byLanguage: [
      { language: 'TypeScript', files: 1, code: 50, comment: 10, blank: 5, total: 65 },
    ],
    totals: {
      files: 1,
      total: 65,
      code: 50,
      blank: 5,
      comment: 10,
    },
  },
  complexity: {
    files: [],
    projectAvg: 1.5,
    hotspots: [
        {
            path: '/test/project/complex.ts',
            language: 'TypeScript',
            maxComplexity: 15,
            avgComplexity: 5,
            functions: [{ name: 'complexFn', line: 10, complexity: 15 }]
        }
    ],
  },
  duplication: {
    blocks: [
        {
            hash: 'abc',
            lines: 20,
            occurrences: [
                { path: '/test/project/dup1.ts', startLine: 10 },
                { path: '/test/project/dup2.ts', startLine: 15 }
            ]
        }
    ],
    duplicatedLines: 40,
    totalLines: 100,
    duplicationRate: 40,
  },
  deadCode: {
    deadExports: [
        { path: '/test/project/dead.ts', symbol: 'unusedFn', line: 5, exportType: 'function' }
    ],
    totalExports: 10,
    deadRatio: 10,
  },
  dependencies: {
    manifests: [
        {
            kind: 'npm',
            path: '/test/project/package.json',
            hasLockFile: true,
            dependencies: ['react'],
            devDependencies: ['typescript']
        }
    ],
    totalDependencies: 1,
    totalDevDependencies: 1,
    missingLockFiles: [],
  },
  score: {
    score: 95,
    grade: 'A+',
    breakdown: {
      commentCoverage: 100,
      complexity: 100,
      duplication: 100,
      deadCode: 100,
    },
    fileScores: [],
    worstFiles: [
        { path: '/test/project/bad.ts', score: 40, grade: 'F', penalties: ['Complexity', 'Duplication'] }
    ],
  },
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('htmlReporter', () => {
  it('renders basic HTML structure', () => {
    const html = renderHtml(MOCK_REPORT);
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<title>Code Audit — project</title>');
    expect(html).toContain('<h1>Code Audit — project</h1>');
    expect(html).toContain('Generated by codelumos');
  });

  it('escapes special characters in project root', () => {
    const report = { ...MOCK_REPORT, rootDir: '/test/<script>' };
    const html = renderHtml(report);
    expect(html).toContain('&lt;script&gt;');
    expect(html).not.toContain('<script>');
  });

  it('renders language breakdown', () => {
    const html = renderHtml(MOCK_REPORT);
    expect(html).toContain('TypeScript');
    expect(html).toContain('<td>50</td>'); // code lines
  });

  it('renders complexity hotspots when present', () => {
    const html = renderHtml(MOCK_REPORT);
    expect(html).toContain('<h2>Complexity Hotspots</h2>');
    expect(html).toContain('complex.ts');
    expect(html).toContain('<td>15</td>'); // max complexity
  });

  it('renders duplicated blocks when present', () => {
    const html = renderHtml(MOCK_REPORT);
    expect(html).toContain('<h2>Duplicated Blocks</h2>');
    expect(html).toContain('dup1.ts:10');
    expect(html).toContain('dup2.ts:15');
  });

  it('renders dead code when present', () => {
    const html = renderHtml(MOCK_REPORT);
    expect(html).toContain('<h2>Potentially Dead Exports</h2>');
    expect(html).toContain('unusedFn');
    expect(html).toContain('dead.ts');
  });

  it('renders dependencies when present', () => {
    const html = renderHtml(MOCK_REPORT);
    expect(html).toContain('<h2>Dependencies</h2>');
    expect(html).toContain('package.json');
    expect(html).toContain('npm');
  });

  it('renders files needing attention when present', () => {
    const html = renderHtml(MOCK_REPORT);
    expect(html).toContain('<h2>Files Needing Attention</h2>');
    expect(html).toContain('bad.ts');
    expect(html).toContain('grade-f');
  });

  it('omits sections when data is empty', () => {
    const emptyReport: AuditReport = {
        ...MOCK_REPORT,
        complexity: { ...MOCK_REPORT.complexity, hotspots: [] },
        duplication: { ...MOCK_REPORT.duplication, blocks: [] },
        deadCode: { ...MOCK_REPORT.deadCode, deadExports: [] },
        dependencies: { ...MOCK_REPORT.dependencies, manifests: [] },
        score: { ...MOCK_REPORT.score, worstFiles: [] },
    };

    const html = renderHtml(emptyReport);
    expect(html).not.toContain('<h2>Complexity Hotspots</h2>');
    expect(html).not.toContain('<h2>Duplicated Blocks</h2>');
    expect(html).not.toContain('<h2>Potentially Dead Exports</h2>');
    expect(html).not.toContain('<h2>Dependencies</h2>');
    expect(html).not.toContain('<h2>Files Needing Attention</h2>');
  });

  it('escapes user input in tables', () => {
     const maliciousReport = {
         ...MOCK_REPORT,
         loc: {
             ...MOCK_REPORT.loc,
             byLanguage: [{ language: '<script>alert(1)</script>', files: 1, total: 10, code: 5, comment: 2, blank: 3 }]
         }
     };
     const html = renderHtml(maliciousReport);
     expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
     expect(html).not.toContain('<script>alert(1)</script>');
  });

  it('renders score with correct class', () => {
      const html = renderHtml(MOCK_REPORT);
      expect(html).toContain('grade-badge grade-a'); // MOCK_REPORT has A+
      expect(html).toContain('95');
  });
});
